// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
//.............


// import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"
// import "./globals.css"

// // import Header from "@/components/layout/Header"
// // import Footer from "@/components/layout/Footer"

// const geistSans = Geist({
//   variable: "--font-sans",
//   subsets: ["latin"],
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// })

// export const metadata: Metadata = {
//   title: {
//     default: "AllwinTech",
//     template: "%s | AllwinTech",
//   },
//   description:
//     "AllwinTech provides modern software development, web solutions, and digital services for businesses.",
//   keywords: [
//     "AllwinTech",
//     "Software Development",
//     "Web Development",
//     "Digital Solutions",
//   ],
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
//       >

//         {/* <Header /> */}

//         <main>
//           {children}
//         </main>

//         {/* <Footer /> */}

//       </body>
//     </html>
//   )
// }

//............

// import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"
// import "./globals.css"

// import { ThemeProvider } from "@/components/providers/theme-provider"
// import Header from "@/components/layout/header"
// import Footer from "@/components/layout/Footer"
// import Loader from "@/components/Loader"

// const geistSans = Geist({
//   variable: "--font-sans",
//   subsets: ["latin"],
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// })

// export const metadata: Metadata = {
//   title: {
//     default: "AllwinTech",
//     template: "%s | AllwinTech",
//   },
//   description:
//     "AllwinTech provides modern software development, web solutions, and digital services for businesses.",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
//       >
       
//         <ThemeProvider>

//           {/* Header */}
// <Header/>
//           <main>
//             {children}
//           </main>

//           {/* Footer */}
// <Footer/>
//         </ThemeProvider>
//       </body>
//     </html>
//   )
// }

//........above code is good

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/providers/theme-provider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/Footer";
import ClientLayout from "./ClientLayout";

// ✅ import client wrapper
// import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "JK Enterprises",
    template: "%s | JK Enterprises",
  },
  description:
    "JK Enterprises provides high-performance industrial printing solutions, including UV, Eco-Solvent, and DTF printers.",
  icons: {
    icon: "/logo/jklogo.webp",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ThemeProvider>
          <ClientLayout>
          <Header />

          {/* 🔥 ALL FEATURES HERE */}
          
            <main>{children}</main>
         

          <Footer />
           </ClientLayout>

        </ThemeProvider>
      </body>
    </html>
  );
}